services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ENVIRONMENT=production
      - PORT=8090
      - TRUSTED_PROXIES=${TRUSTED_PROXIES:-172.16.0.0/12,192.168.0.0/16,10.0.0.0/8,127.0.0.1}
    volumes:
      - backend_data:/app/data
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - API_HOST=backend
      - API_PORT=8090
      - API_PROTOCOL=https
    depends_on:
      backend:
        condition: service_healthy

volumes:
  backend_data:
