services:
  backend:
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "8090:8090"
    environment:
      - JWT_SECRET=local_dev_secret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - ALLOWED_ORIGINS=http://localhost:4320
      - ENVIRONMENT=development
      - PORT=8090
    volumes:
      - backend_data:/app/data
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build:
      context: ./web
      target: development
      dockerfile: Dockerfile.dev
    ports:
      - "4320:4320"
    environment:
      - PUBLIC_API_URL=http://localhost:8090
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    command: pnpm dev --host
    depends_on:
      backend:
        condition: service_healthy

volumes:
  backend_data:
  web_node_modules:
