services:
  backend:
    build: ./backend
    ports:
      - "8092:8092"
    environment:
      - JWT_SECRET=local_dev_secret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - ALLOWED_ORIGINS=http://localhost:4321
      - ENVIRONMENT=development
      - PORT=8092
    volumes:
      - backend_data:/app/data
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8090/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build:
      context: ./web
      target: development
    ports:
      - "4321:4321"
    environment:
      - PUBLIC_API_URL=http://localhost:8092
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    command: pnpm dev --host
    depends_on:
      backend:
        condition: service_healthy

volumes:
  backend_data:
  web_node_modules:
