services:
  backend:
    build: ./backend
    ports:
      - "8090:8090"
    environment:
      - JWT_SECRET=local_dev_secret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - ALLOWED_ORIGINS=http://localhost:8080
      - ENVIRONMENT=development
      - PORT=8090
    volumes:
      - backend_data:/app/data
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8090/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: ./web
    ports:
      - "8080:80"
    environment:
      - API_HOST=backend
      - API_PORT=8090
      - API_PROTOCOL=http
    depends_on:
      backend:
        condition: service_healthy

volumes:
  backend_data:
